#include <CLI/CLI.hpp>

#include <algorithm>
#include <array>
#include <chrono>
#include <cctype>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <future>
#include <iomanip>
#include <iostream>
#include <mutex>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <system_error>
#include <thread>
#include <type_traits>
#include <utility>
#include <vector>

#include <mailxx/detail/log.hpp>
#include <mailxx/mailxx.hpp>

namespace
{

using namespace std::string_view_literals;

struct global_options
{
    std::string log_level{"debug"};
    bool trace{false};
    bool show_source{true};
    bool stop_on_error{false};
    int suite_timeout_sec{30};
    std::string log_file;
};

struct tls_cli_options
{
    std::string host{"localhost"};
    std::string port;
    std::string tls_mode{"none"};
    std::string sni;
    bool insecure{false};
    bool allow_self_signed{false};
    bool allow_expired{false};
    bool use_default_verify_paths{true};
    std::vector<std::string> ca_files;
    std::vector<std::string> ca_paths;
};

struct smtp_cli_options
{
    tls_cli_options tls;
    std::string hello_domain{"localhost"};
    std::string username;
    std::string secret;
    std::string auth_method{"auto_detect"};
    bool allow_cleartext_auth{false};
    bool require_tls_for_auth{true};
    std::string from;
    std::string from_name{"mailxx CLI11"};
    std::vector<std::string> to;
    std::string to_name{"mailxx recipient"};
    std::string subject{"mailxx real-world validation"};
    std::string body{"Message generated by mailxx_realworld_cli."};
    std::vector<std::string> attachments;
};

struct imap_cli_options
{
    tls_cli_options tls;
    std::string username;
    std::string secret;
    std::string auth_method{"login"};
    bool allow_cleartext_auth{false};
    bool require_tls_for_auth{true};
    std::string mailbox{"INBOX"};
    std::string search{"ALL"};
    std::optional<std::uint32_t> uid;
};

struct pop3_cli_options
{
    tls_cli_options tls;
    std::string username;
    std::string secret;
    std::string auth_method{"login"};
    bool allow_cleartext_auth{false};
    bool require_tls_for_auth{true};
    unsigned int message_no{1};
    unsigned int top_lines{20};
};

enum class scenario_status
{
    passed,
    failed,
    skipped
};

struct scenario_result
{
    std::string name;
    scenario_status status;
    std::string detail;
};

[[nodiscard]] std::string lower_copy(std::string value)
{
    std::transform(value.begin(), value.end(), value.begin(),
        [](unsigned char ch) { return static_cast<char>(std::tolower(ch)); });
    return value;
}

[[nodiscard]] std::string sanitize_inline(std::string value)
{
    std::replace(value.begin(), value.end(), '\r', ' ');
    std::replace(value.begin(), value.end(), '\n', ' ');
    return value;
}

[[nodiscard]] std::string truncate_copy(std::string_view value, std::size_t max_len = 140)
{
    std::string out(value);
    if (out.size() <= max_len)
        return sanitize_inline(std::move(out));
    out.resize(max_len);
    out += "...";
    return sanitize_inline(std::move(out));
}

[[nodiscard]] std::string join_strings(const std::vector<std::string>& values, std::string_view separator = ", ")
{
    std::ostringstream oss;
    for (std::size_t i = 0; i < values.size(); ++i)
    {
        if (i != 0)
            oss << separator;
        oss << values[i];
    }
    return oss.str();
}

[[nodiscard]] bool looks_like_email(std::string_view value)
{
    return value.find('@') != std::string_view::npos;
}

[[nodiscard]] std::string now_utc_string()
{
    const auto now = std::chrono::system_clock::now();
    const auto time = std::chrono::system_clock::to_time_t(now);
    std::tm tm_buf{};
#ifdef _WIN32
    gmtime_s(&tm_buf, &time);
#else
    gmtime_r(&time, &tm_buf);
#endif
    std::ostringstream oss;
    oss << std::put_time(&tm_buf, "%Y-%m-%d %H:%M:%S UTC");
    return oss.str();
}

[[nodiscard]] std::string scenario_status_to_string(scenario_status status)
{
    switch (status)
    {
        case scenario_status::passed: return "PASS";
        case scenario_status::failed: return "FAIL";
        case scenario_status::skipped: return "SKIP";
    }
    return "UNKNOWN";
}

class log_sink
{
public:
    log_sink(std::string log_file, bool show_source)
        : show_source_(show_source)
    {
        if (!log_file.empty())
        {
            std::filesystem::path path(log_file);
            if (path.has_parent_path())
                std::filesystem::create_directories(path.parent_path());
            file_.open(path, std::ios::out | std::ios::trunc);
            if (!file_)
                throw std::runtime_error("Unable to open log file: " + path.string());
        }
    }

    void write(const mailxx::log::entry& entry)
    {
        const std::string line = format(entry);
        std::lock_guard lock(mutex_);
        std::cerr << line << '\n';
        if (file_)
        {
            file_ << line << '\n';
            file_.flush();
        }
    }

private:
    [[nodiscard]] std::string format_timestamp(const std::chrono::system_clock::time_point& tp) const
    {
        const auto time = std::chrono::system_clock::to_time_t(tp);
        const auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(tp.time_since_epoch()) % 1000;
        std::tm tm_buf{};
#ifdef _WIN32
        localtime_s(&tm_buf, &time);
#else
        localtime_r(&time, &tm_buf);
#endif

        std::ostringstream oss;
        oss << std::put_time(&tm_buf, "%Y-%m-%d %H:%M:%S")
            << '.' << std::setw(3) << std::setfill('0') << ms.count();
        return oss.str();
    }

    [[nodiscard]] std::string thread_id_string() const
    {
        std::ostringstream oss;
        oss << std::this_thread::get_id();
        return oss.str();
    }

    [[nodiscard]] std::string format(const mailxx::log::entry& entry) const
    {
        std::ostringstream oss;
        oss << '[' << format_timestamp(entry.timestamp) << "] "
            << '[' << mailxx::log::level_to_string(entry.lvl) << "] "
            << "[tid=" << thread_id_string() << "] ";

        if (entry.trace_info)
        {
            const char* direction = entry.trace_info->dir == mailxx::log::direction::send ? ">>>" : "<<<";
            oss << entry.trace_info->protocol << ' ' << direction << ' '
                << truncate_copy(entry.trace_info->data, 500);
        }
        else
        {
            oss << entry.message;
        }

        if (show_source_)
            oss << " (" << entry.location.file_name() << ':' << entry.location.line() << ')';

        return oss.str();
    }

    bool show_source_{true};
    std::mutex mutex_;
    std::ofstream file_;
};

class scenario_recorder
{
public:
    scenario_recorder(std::string suite_name, bool stop_on_error)
        : suite_name_(std::move(suite_name)),
          stop_on_error_(stop_on_error)
    {
    }

    void pass(std::string name, std::string detail)
    {
        results_.push_back({std::move(name), scenario_status::passed, std::move(detail)});
        const auto& result = results_.back();
        MAILXX_LOG_INFO("CLI", result.name << " ok - " << result.detail);
    }

    void skip(std::string name, std::string detail)
    {
        results_.push_back({std::move(name), scenario_status::skipped, std::move(detail)});
        const auto& result = results_.back();
        MAILXX_LOG_WARN("CLI", result.name << " skipped - " << result.detail);
    }

    [[nodiscard]] bool fail(std::string name, const mailxx::error_info& err)
    {
        std::ostringstream detail;
        detail << mailxx::to_string(err.code) << " - " << err.message;
        if (!err.sys.message().empty())
            detail << " [sys=" << err.sys.message() << ']';

        results_.push_back({std::move(name), scenario_status::failed, detail.str()});
        const auto& result = results_.back();
        MAILXX_LOG_ERROR("CLI", result.name << " failed - " << result.detail);
        if (!err.detail.empty())
            MAILXX_LOG_DEBUG("CLI", result.name << " detail=" << sanitize_inline(err.detail));
        MAILXX_LOG_DEBUG("CLI", result.name << " where=" << err.where.file_name() << ':' << err.where.line());
        return !stop_on_error_;
    }

    [[nodiscard]] bool has_failures() const
    {
        return std::any_of(results_.begin(), results_.end(), [](const scenario_result& result)
        {
            return result.status == scenario_status::failed;
        });
    }

    [[nodiscard]] int exit_code() const
    {
        return has_failures() ? 2 : 0;
    }

    void print_summary() const
    {
        std::size_t passed = 0;
        std::size_t failed = 0;
        std::size_t skipped = 0;

        for (const auto& result : results_)
        {
            switch (result.status)
            {
                case scenario_status::passed: ++passed; break;
                case scenario_status::failed: ++failed; break;
                case scenario_status::skipped: ++skipped; break;
            }
        }

        std::cout << "\n=== " << suite_name_ << " Summary ===\n";
        for (const auto& result : results_)
            std::cout << scenario_status_to_string(result.status) << "  " << result.name << "  " << result.detail << '\n';
        std::cout << "Totals: passed=" << passed << " failed=" << failed << " skipped=" << skipped << '\n';
    }

private:
    std::string suite_name_;
    bool stop_on_error_{false};
    std::vector<scenario_result> results_;
};

template<typename T, typename Describe>
[[nodiscard]] bool record_result(
    scenario_recorder& recorder,
    const std::string& step,
    mailxx::result<T>&& result,
    Describe&& describe_success)
{
    if (!result)
        return recorder.fail(step, result.error());

    if constexpr (std::is_void_v<T>)
        recorder.pass(step, describe_success());
    else
        recorder.pass(step, describe_success(*result));
    return true;
}

[[nodiscard]] mailxx::log::level parse_log_level(std::string value)
{
    value = lower_copy(std::move(value));
    if (value == "trace") return mailxx::log::level::trace;
    if (value == "debug") return mailxx::log::level::debug;
    if (value == "info") return mailxx::log::level::info;
    if (value == "warn") return mailxx::log::level::warn;
    if (value == "error") return mailxx::log::level::error;
    if (value == "fatal") return mailxx::log::level::fatal;
    if (value == "off") return mailxx::log::level::off;
    throw std::runtime_error("Unsupported log level: " + value);
}

[[nodiscard]] mailxx::net::tls_mode parse_tls_mode(std::string value)
{
    value = lower_copy(std::move(value));
    if (value == "none") return mailxx::net::tls_mode::none;
    if (value == "starttls") return mailxx::net::tls_mode::starttls;
    if (value == "implicit") return mailxx::net::tls_mode::implicit;
    throw std::runtime_error("Unsupported TLS mode: " + value);
}

[[nodiscard]] std::string default_smtp_port(mailxx::net::tls_mode mode)
{
    switch (mode)
    {
        case mailxx::net::tls_mode::none: return "25";
        case mailxx::net::tls_mode::starttls: return "587";
        case mailxx::net::tls_mode::implicit: return "465";
    }
    return "25";
}

[[nodiscard]] std::string default_imap_port(mailxx::net::tls_mode mode)
{
    switch (mode)
    {
        case mailxx::net::tls_mode::none: return "143";
        case mailxx::net::tls_mode::starttls: return "143";
        case mailxx::net::tls_mode::implicit: return "993";
    }
    return "143";
}

[[nodiscard]] std::string default_pop3_port(mailxx::net::tls_mode mode)
{
    switch (mode)
    {
        case mailxx::net::tls_mode::none: return "110";
        case mailxx::net::tls_mode::starttls: return "110";
        case mailxx::net::tls_mode::implicit: return "995";
    }
    return "110";
}

[[nodiscard]] mailxx::smtp::auth_method parse_smtp_auth_method(std::string value)
{
    value = lower_copy(std::move(value));
    if (value == "auto_detect") return mailxx::smtp::auth_method::auto_detect;
    if (value == "plain") return mailxx::smtp::auth_method::plain;
    if (value == "login") return mailxx::smtp::auth_method::login;
    if (value == "xoauth2") return mailxx::smtp::auth_method::xoauth2;
    throw std::runtime_error("Unsupported SMTP auth method: " + value);
}

[[nodiscard]] mailxx::imap::auth_method parse_imap_auth_method(std::string value)
{
    value = lower_copy(std::move(value));
    if (value == "auto_detect") return mailxx::imap::auth_method::auto_detect;
    if (value == "plain") return mailxx::imap::auth_method::plain;
    if (value == "login") return mailxx::imap::auth_method::login;
    if (value == "xoauth2") return mailxx::imap::auth_method::xoauth2;
    throw std::runtime_error("Unsupported IMAP auth method: " + value);
}

[[nodiscard]] mailxx::pop3::pop3_base::auth_method_t parse_pop3_auth_method(std::string value)
{
    value = lower_copy(std::move(value));
    if (value == "login") return mailxx::pop3::pop3_base::auth_method_t::LOGIN;
    if (value == "plain") return mailxx::pop3::pop3_base::auth_method_t::PLAIN;
    if (value == "xoauth2") return mailxx::pop3::pop3_base::auth_method_t::XOAUTH2;
    if (value == "apop") return mailxx::pop3::pop3_base::auth_method_t::APOP;
    throw std::runtime_error("Unsupported POP3 auth method: " + value);
}

[[nodiscard]] mailxx::net::tls_options make_tls_options(const tls_cli_options& cli)
{
    mailxx::net::tls_options tls;
    tls.verify = cli.insecure ? mailxx::net::verify_mode::none : mailxx::net::verify_mode::peer;
    tls.verify_host = !cli.insecure;
    tls.use_default_verify_paths = cli.use_default_verify_paths;
    tls.ca_files = cli.ca_files;
    tls.ca_paths = cli.ca_paths;
    tls.allow_self_signed = cli.allow_self_signed;
    tls.allow_expired = cli.allow_expired;
    return tls;
}

template<typename Options>
void apply_shared_security_options(
    Options& options,
    const tls_cli_options& tls_cli,
    bool allow_cleartext_auth,
    bool require_tls_for_auth)
{
    options.default_sni = tls_cli.sni;
    options.auto_starttls = false;
    options.allow_cleartext_auth = allow_cleartext_auth;
    options.require_tls_for_auth = allow_cleartext_auth ? false : require_tls_for_auth;
    options.default_tls_mode = parse_tls_mode(tls_cli.tls_mode);
    options.redact_secrets_in_trace = true;
    options.tls = make_tls_options(tls_cli);
}

[[nodiscard]] std::string summarize_smtp_reply(const mailxx::smtp::reply& reply)
{
    std::ostringstream oss;
    oss << "status=" << reply.status << " lines=" << reply.lines.size();
    if (!reply.lines.empty())
        oss << " first=\"" << truncate_copy(reply.lines.front()) << '"';
    return oss.str();
}

[[nodiscard]] std::string summarize_smtp_capabilities(const mailxx::smtp::client& client)
{
    std::ostringstream oss;
    const auto size_limit = client.get_size_limit();
    oss << "PIPELINING=" << (client.supports_pipelining() ? "yes" : "no")
        << " SIZE=";
    if (size_limit.has_limit())
        oss << size_limit.max_size;
    else
        oss << "unknown";
    oss << " 8BITMIME=" << (client.supports_8bitmime() ? "yes" : "no")
        << " SMTPUTF8=" << (client.supports_smtputf8() ? "yes" : "no")
        << " DSN=" << (client.supports_dsn() ? "yes" : "no");
    return oss.str();
}

[[nodiscard]] std::string summarize_imap_status(mailxx::imap::status status)
{
    switch (status)
    {
        case mailxx::imap::status::ok: return "ok";
        case mailxx::imap::status::no: return "no";
        case mailxx::imap::status::bad: return "bad";
        case mailxx::imap::status::preauth: return "preauth";
        case mailxx::imap::status::bye: return "bye";
        case mailxx::imap::status::unknown: return "unknown";
    }
    return "unknown";
}

[[nodiscard]] std::string summarize_imap_response(const mailxx::imap::response& response)
{
    std::ostringstream oss;
    oss << "status=" << summarize_imap_status(response.st)
        << " tag=" << response.tag
        << " text=\"" << truncate_copy(response.text) << '"'
        << " untagged=" << response.untagged_lines.size()
        << " tagged=" << response.tagged_lines.size()
        << " literals=" << response.literals.size();
    return oss.str();
}

[[nodiscard]] std::string summarize_pop3_capabilities(const mailxx::pop3::capabilities& caps)
{
    std::ostringstream oss;
    oss << "STLS=" << (caps.stls ? "yes" : "no")
        << " UIDL=" << (caps.uidl ? "yes" : "no")
        << " TOP=" << (caps.top ? "yes" : "no");
    if (!caps.sasl_mechanisms.empty())
        oss << " SASL=" << join_strings(caps.sasl_mechanisms, "/");
    return oss.str();
}

[[nodiscard]] std::string summarize_mailbox_stat(const mailxx::imap::mailbox_stat& stat)
{
    std::ostringstream oss;
    oss << "messages=" << stat.messages_no
        << " recent=" << stat.recent
        << " unseen=" << stat.unseen
        << " uid_next=" << stat.uid_next
        << " uid_validity=" << stat.uid_validity;
    return oss.str();
}

[[nodiscard]] std::string summarize_pop3_stat(const mailxx::pop3::mailbox_stat& stat)
{
    std::ostringstream oss;
    oss << "messages=" << stat.messages_no << " size=" << stat.mailbox_size;
    return oss.str();
}

[[nodiscard]] std::string effective_sender(const smtp_cli_options& options)
{
    if (!options.from.empty())
        return options.from;
    if (looks_like_email(options.username))
        return options.username;
    return {};
}

[[nodiscard]] std::string normalize_crlf(std::string_view text)
{
    std::string out;
    out.reserve(text.size() + 8);
    for (std::size_t i = 0; i < text.size(); ++i)
    {
        const char ch = text[i];
        if (ch == '\r')
        {
            out += "\r";
            if (i + 1 < text.size() && text[i + 1] == '\n')
            {
                out += "\n";
                ++i;
            }
            else
            {
                out += "\n";
            }
            continue;
        }
        if (ch == '\n')
        {
            out += "\r\n";
            continue;
        }
        out.push_back(ch);
    }
    return out;
}

[[nodiscard]] std::vector<std::string> effective_recipients(const smtp_cli_options& options)
{
    if (!options.to.empty())
        return options.to;
    const auto sender = effective_sender(options);
    if (!sender.empty())
        return {sender};
    return {};
}

[[nodiscard]] std::vector<std::filesystem::path> effective_attachments(const smtp_cli_options& options)
{
    std::vector<std::filesystem::path> files;
    for (const auto& attachment : options.attachments)
        files.emplace_back(attachment);

    if (!files.empty())
        return files;

#ifdef MAILXX_REPO_ROOT
    const std::filesystem::path repo_root(MAILXX_REPO_ROOT);
    const std::array<std::filesystem::path, 2> bundled = {
        repo_root / "examples" / "aleph0.png",
        repo_root / "examples" / "infinity.png"
    };
    for (const auto& candidate : bundled)
    {
        if (std::filesystem::exists(candidate))
            files.push_back(candidate);
    }
#endif

    return files;
}

[[nodiscard]] mailxx::message::content_type_t infer_content_type(const std::filesystem::path& path)
{
    const std::string ext = lower_copy(path.extension().string());
    using media_type_t = mailxx::message::media_type_t;
    using content_type_t = mailxx::message::content_type_t;

    if (ext == ".png") return content_type_t(media_type_t::IMAGE, "png");
    if (ext == ".jpg" || ext == ".jpeg") return content_type_t(media_type_t::IMAGE, "jpeg");
    if (ext == ".gif") return content_type_t(media_type_t::IMAGE, "gif");
    if (ext == ".pdf") return content_type_t(media_type_t::APPLICATION, "pdf");
    if (ext == ".html" || ext == ".htm") return content_type_t(media_type_t::TEXT, "html", "utf-8");
    if (ext == ".json") return content_type_t(media_type_t::APPLICATION, "json");
    if (ext == ".txt" || ext == ".log") return content_type_t(media_type_t::TEXT, "plain", "utf-8");
    return content_type_t(media_type_t::APPLICATION, "octet-stream");
}

[[nodiscard]] mailxx::result<mailxx::message> build_message(
    const smtp_cli_options& options,
    std::string_view scenario,
    bool utf8_content = false,
    const std::vector<std::filesystem::path>& attachments = {},
    bool large_body = false)
{
    const auto sender = effective_sender(options);
    const auto recipients = effective_recipients(options);

    if (sender.empty())
        return mailxx::fail<mailxx::message>(mailxx::errc::smtp_invalid_state,
            "Missing sender address for SMTP send scenarios.",
            "Set --from or provide --username with an email address.");
    if (recipients.empty())
        return mailxx::fail<mailxx::message>(mailxx::errc::smtp_invalid_state,
            "Missing recipient address for SMTP send scenarios.",
            "Set at least one --to recipient.");

    mailxx::message message;
    message.from(mailxx::mail_address(mailxx::string_t(options.from_name), sender));
    for (const auto& recipient : recipients)
        message.add_recipient(mailxx::mail_address(mailxx::string_t(options.to_name), recipient));

    std::string subject = options.subject + " [" + std::string(scenario) + "]";
    std::string body = normalize_crlf(options.body);
    if (utf8_content)
    {
        const std::string utf8_suffix =
            " Validation UTF-8: caf" "\xC3\xA9"
            ", d" "\xC3\xA9" "j" "\xC3\xA0"
            ", fa" "\xC3\xA7" "ade.";
        subject += utf8_suffix;
        body += "\r\n" + utf8_suffix;
    }

    std::ostringstream oss;
    oss << body
        << "\r\nScenario: " << scenario
        << "\r\nGenerated-At: " << now_utc_string()
        << "\r\nRecipients: " << join_strings(recipients)
        << "\r\n";

    if (large_body)
    {
        oss << "Large-Body: enabled\r\n";
        for (int i = 0; i < 128; ++i)
            oss << "Chunk-" << std::setw(3) << std::setfill('0') << i << ": "
                << "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                << "\r\n";
    }

    message.subject(subject);
    message.content(oss.str());

    for (const auto& attachment : attachments)
    {
        const auto result = message.attach_file(
            attachment,
            mailxx::string_t(attachment.filename().string()),
            infer_content_type(attachment));
        if (!result)
            return mailxx::fail<mailxx::message>(result.error());
    }

    return mailxx::ok(std::move(message));
}

[[nodiscard]] mailxx::smtp::envelope build_envelope(const smtp_cli_options& options)
{
    mailxx::smtp::envelope env;
    env.mail_from = effective_sender(options);
    env.rcpt_to = effective_recipients(options);
    return env;
}

[[nodiscard]] std::string smtp_connection_summary(const smtp_cli_options& options, const std::string& port)
{
    std::ostringstream oss;
    oss << "host=" << options.tls.host
        << " port=" << port
        << " tls=" << options.tls.tls_mode
        << " insecure=" << (options.tls.insecure ? "yes" : "no")
        << " auth=" << (options.username.empty() ? "disabled" : options.auth_method);
    return oss.str();
}

[[nodiscard]] std::string imap_connection_summary(const imap_cli_options& options, const std::string& port)
{
    std::ostringstream oss;
    oss << "host=" << options.tls.host
        << " port=" << port
        << " tls=" << options.tls.tls_mode
        << " mailbox=" << options.mailbox
        << " auth=" << (options.username.empty() ? "disabled" : options.auth_method);
    return oss.str();
}

[[nodiscard]] std::string pop3_connection_summary(const pop3_cli_options& options, const std::string& port)
{
    std::ostringstream oss;
    oss << "host=" << options.tls.host
        << " port=" << port
        << " tls=" << options.tls.tls_mode
        << " message_no=" << options.message_no
        << " auth=" << (options.username.empty() ? "disabled" : options.auth_method);
    return oss.str();
}

void configure_logging(const global_options& options)
{
    auto sink = std::make_shared<log_sink>(options.log_file, options.show_source);
    auto& logger = mailxx::log::logger::instance();
    logger.set_level(parse_log_level(options.log_level));
    logger.set_trace_enabled(options.trace);
    logger.set_callback([sink](const mailxx::log::entry& entry)
    {
        sink->write(entry);
    });
}

template<typename Options>
void add_common_security_flags(CLI::App& app, Options& options)
{
    app.add_option("--host", options.tls.host, "Server hostname or IP");
    app.add_option("--port", options.tls.port, "Server port");
    app.add_option("--tls-mode", options.tls.tls_mode, "TLS mode: none, starttls, implicit")
        ->check(CLI::IsMember({"none", "starttls", "implicit"}, CLI::ignore_case));
    app.add_option("--sni", options.tls.sni, "Override TLS SNI hostname");
    app.add_flag("--insecure", options.tls.insecure, "Disable certificate and host verification");
    app.add_flag("--allow-self-signed", options.tls.allow_self_signed, "Allow self-signed certificates");
    app.add_flag("--allow-expired", options.tls.allow_expired, "Allow expired certificates");
    app.add_flag_function("--no-default-ca",
        [&options](std::int64_t)
        {
            options.tls.use_default_verify_paths = false;
        },
        "Disable default CA trust paths");
    app.add_option("--ca-file", options.tls.ca_files, "Additional CA file (repeatable)")
        ->check(CLI::ExistingFile);
    app.add_option("--ca-path", options.tls.ca_paths, "Additional CA directory (repeatable)")
        ->check(CLI::ExistingDirectory);
}

template<typename Options>
void add_auth_flags(CLI::App& app, Options& options, const std::vector<std::string>& methods)
{
    app.add_option("--username", options.username, "Username or mailbox login");
    app.add_option("--secret", options.secret, "Password or bearer token");
    app.add_option("--auth-method", options.auth_method, "Authentication method")
        ->check(CLI::IsMember(methods, CLI::ignore_case));
    app.add_flag("--allow-cleartext-auth", options.allow_cleartext_auth, "Allow authentication without TLS");
    app.add_flag_function("--no-require-tls-auth",
        [&options](std::int64_t)
        {
            options.require_tls_for_auth = false;
        },
        "Do not enforce TLS before AUTH");
}

template<typename Runner>
int run_suite(const std::string& suite_name, bool stop_on_error, int suite_timeout_sec, Runner&& runner)
{
    scenario_recorder recorder(suite_name, stop_on_error);
    mailxx::asio::io_context io;
    auto future = mailxx::asio::co_spawn(
        io,
        runner(recorder),
        mailxx::asio::use_future);
    std::thread io_thread([&io]()
    {
        io.run();
    });
    const auto wait_status = future.wait_for(std::chrono::seconds(suite_timeout_sec));
    if (wait_status == std::future_status::timeout)
    {
        (void)recorder.fail("suite_timeout", mailxx::make_error(
            mailxx::errc::net_timeout,
            "Suite timed out.",
            "timeout_seconds=" + std::to_string(suite_timeout_sec) + "\nA command likely blocked waiting on the server."));
        io.stop();
        io_thread.join();
        recorder.print_summary();
        return 124;
    }
    io_thread.join();
    const int exit_code = future.get();
    recorder.print_summary();
    return exit_code;
}

mailxx::asio::awaitable<int> run_smtp_suite(const smtp_cli_options& options, scenario_recorder& recorder);
mailxx::asio::awaitable<int> run_imap_suite(const imap_cli_options& options, scenario_recorder& recorder);
mailxx::asio::awaitable<int> run_pop3_suite(const pop3_cli_options& options, scenario_recorder& recorder);

mailxx::asio::awaitable<int> run_smtp_suite(const smtp_cli_options& options, scenario_recorder& recorder)
{
    const auto tls_mode = parse_tls_mode(options.tls.tls_mode);
    const std::string port = options.tls.port.empty() ? default_smtp_port(tls_mode) : options.tls.port;
    const std::string sni = options.tls.sni.empty() ? options.tls.host : options.tls.sni;

    MAILXX_LOG_INFO("CLI", "Starting SMTP suite with " << smtp_connection_summary(options, port));

    mailxx::smtp::options client_options;
    apply_shared_security_options(client_options, options.tls, options.allow_cleartext_auth, options.require_tls_for_auth);
    mailxx::smtp::client client(co_await mailxx::asio::this_coro::executor, client_options);
    mailxx::asio::ssl::context tls_ctx(mailxx::asio::ssl::context::tls_client);

    bool connected = false;
    bool greeted = false;

    auto connect_res = co_await client.connect(options.tls.host, port, tls_mode,
        tls_mode == mailxx::net::tls_mode::none ? nullptr : &tls_ctx, sni);
    if (!record_result(recorder, "connect", std::move(connect_res), [&]
        {
            connected = true;
            return "Connected to " + options.tls.host + ":" + port;
        }))
    {
        co_return recorder.exit_code();
    }

    auto greeting_res = co_await client.read_greeting();
    if (!record_result(recorder, "greeting", std::move(greeting_res), [&]
        {
            greeted = true;
            return "SMTP greeting read successfully";
        }))
    {
        co_return recorder.exit_code();
    }

    auto ehlo_res = co_await client.ehlo(options.hello_domain);
    if (!record_result(recorder, "ehlo", std::move(ehlo_res), [&]
        {
            return "EHLO completed with domain " + options.hello_domain;
        }))
    {
        co_return recorder.exit_code();
    }
    recorder.pass("capabilities_pre_tls", summarize_smtp_capabilities(client));

    if (tls_mode == mailxx::net::tls_mode::starttls)
    {
        auto starttls_res = co_await client.start_tls(tls_ctx, sni);
        if (!record_result(recorder, "starttls", std::move(starttls_res), [&]
            {
                return "TLS upgrade completed";
            }))
        {
            co_return recorder.exit_code();
        }

        auto ehlo_tls_res = co_await client.ehlo(options.hello_domain);
        if (!record_result(recorder, "ehlo_post_tls", std::move(ehlo_tls_res), [&]
            {
                return "EHLO repeated after STARTTLS";
            }))
        {
            co_return recorder.exit_code();
        }
        recorder.pass("capabilities_post_tls", summarize_smtp_capabilities(client));
    }

    if (!options.username.empty() && !options.secret.empty())
    {
        auto auth_res = co_await client.authenticate(
            options.username,
            options.secret,
            parse_smtp_auth_method(options.auth_method));
        if (!record_result(recorder, "auth", std::move(auth_res), [&]
            {
                return "Authenticated as " + options.username;
            }))
        {
            co_return recorder.exit_code();
        }
    }
    else
    {
        recorder.skip("auth", "No --username/--secret provided");
    }

    auto noop_res = co_await client.noop();
    if (!record_result(recorder, "noop", std::move(noop_res), [](const mailxx::smtp::reply& reply)
        {
            return summarize_smtp_reply(reply);
        }))
    {
        co_return recorder.exit_code();
    }

    auto rset_res = co_await client.rset();
    if (!record_result(recorder, "rset", std::move(rset_res), [](const mailxx::smtp::reply& reply)
        {
            return summarize_smtp_reply(reply);
        }))
    {
        co_return recorder.exit_code();
    }

    const auto envelope = build_envelope(options);
    const bool can_send = !envelope.mail_from.empty() && !envelope.rcpt_to.empty();
    if (!can_send)
    {
        recorder.skip("send_simple", "Missing sender/recipient. Set --from/--to or use an email-like --username");
        recorder.skip("send_pipelined", "Missing sender/recipient");
        recorder.skip("send_streaming", "Missing sender/recipient");
        recorder.skip("send_progress", "Missing sender/recipient");
        recorder.skip("send_utf8_content", "Missing sender/recipient");
        recorder.skip("send_attachment", "Missing sender/recipient");
        recorder.skip("send_dsn", "Missing sender/recipient");
    }
    else
    {
        auto simple_message = build_message(options, "send_simple");
        if (!simple_message)
        {
            (void)recorder.fail("send_simple_build", simple_message.error());
            co_return recorder.exit_code();
        }
        auto send_res = co_await client.send(*simple_message);
        if (!record_result(recorder, "send_simple", std::move(send_res), [](const mailxx::smtp::reply& reply)
            {
                return summarize_smtp_reply(reply);
            }))
        {
            co_return recorder.exit_code();
        }

        if (client.supports_pipelining())
        {
            auto pipelined_message = build_message(options, "send_pipelined");
            if (!pipelined_message)
            {
                (void)recorder.fail("send_pipelined_build", pipelined_message.error());
                co_return recorder.exit_code();
            }
            auto pipelined_res = co_await client.send_pipelined(*pipelined_message, envelope);
            if (!record_result(recorder, "send_pipelined", std::move(pipelined_res), [](const mailxx::smtp::reply& reply)
                {
                    return summarize_smtp_reply(reply);
                }))
            {
                co_return recorder.exit_code();
            }
        }
        else
        {
            recorder.skip("send_pipelined", "Server did not advertise PIPELINING");
        }

        auto streaming_message = build_message(options, "send_streaming", false, {}, true);
        if (!streaming_message)
        {
            (void)recorder.fail("send_streaming_build", streaming_message.error());
            co_return recorder.exit_code();
        }
        auto streaming_res = co_await client.send_streaming(envelope, *streaming_message);
        if (!record_result(recorder, "send_streaming", std::move(streaming_res), [](const mailxx::smtp::reply& reply)
            {
                return summarize_smtp_reply(reply);
            }))
        {
            co_return recorder.exit_code();
        }

        auto progress_message = build_message(options, "send_progress", false, {}, true);
        if (!progress_message)
        {
            (void)recorder.fail("send_progress_build", progress_message.error());
            co_return recorder.exit_code();
        }
        auto progress_res = co_await client.send_with_progress(
            *progress_message,
            envelope,
            [](const mailxx::smtp::progress_info_t& progress)
            {
                MAILXX_LOG_DEBUG("CLI", "SMTP progress bytes=" << progress.bytes_transferred
                    << " total=" << progress.total_bytes
                    << " percent=" << progress.percent());
            });
        if (!record_result(recorder, "send_progress", std::move(progress_res), [](const mailxx::smtp::reply& reply)
            {
                return summarize_smtp_reply(reply);
            }))
        {
            co_return recorder.exit_code();
        }

        auto utf8_message = build_message(options, "send_utf8_content", true);
        if (!utf8_message)
        {
            (void)recorder.fail("send_utf8_content_build", utf8_message.error());
            co_return recorder.exit_code();
        }
        auto utf8_res = co_await client.send(*utf8_message, envelope);
        if (!record_result(recorder, "send_utf8_content", std::move(utf8_res), [](const mailxx::smtp::reply& reply)
            {
                return summarize_smtp_reply(reply);
            }))
        {
            co_return recorder.exit_code();
        }

        const auto attachments = effective_attachments(options);
        if (!attachments.empty())
        {
            auto attachment_message = build_message(options, "send_attachment", false, attachments);
            if (!attachment_message)
            {
                (void)recorder.fail("send_attachment_build", attachment_message.error());
                co_return recorder.exit_code();
            }
            auto attachment_res = co_await client.send(*attachment_message, envelope);
            if (!record_result(recorder, "send_attachment", std::move(attachment_res), [&](const mailxx::smtp::reply& reply)
                {
                    std::vector<std::string> names;
                    for (const auto& file : attachments)
                        names.push_back(file.filename().string());
                    return summarize_smtp_reply(reply) + " files=" + join_strings(names);
                }))
            {
                co_return recorder.exit_code();
            }
        }
        else
        {
            recorder.skip("send_attachment", "No --attachment provided and bundled sample files were not found");
        }

        if (client.supports_dsn())
        {
            auto dsn_message = build_message(options, "send_dsn");
            if (!dsn_message)
            {
                (void)recorder.fail("send_dsn_build", dsn_message.error());
                co_return recorder.exit_code();
            }
            mailxx::smtp::envelope_dsn env(envelope, mailxx::smtp::dsn_options::on_failure());
            auto dsn_res = co_await client.send(*dsn_message, env);
            if (!record_result(recorder, "send_dsn", std::move(dsn_res), [](const mailxx::smtp::reply& reply)
                {
                    return summarize_smtp_reply(reply);
                }))
            {
                co_return recorder.exit_code();
            }
        }
        else
        {
            recorder.skip("send_dsn", "Server did not advertise DSN");
        }
    }

    if (connected && greeted)
    {
        auto quit_res = co_await client.quit();
        if (!record_result(recorder, "quit", std::move(quit_res), [](const mailxx::smtp::reply& reply)
            {
                return summarize_smtp_reply(reply);
            }))
        {
            co_return recorder.exit_code();
        }
    }

    co_return recorder.exit_code();
}

mailxx::asio::awaitable<int> run_imap_suite(const imap_cli_options& options, scenario_recorder& recorder)
{
    const auto tls_mode = parse_tls_mode(options.tls.tls_mode);
    const std::string port = options.tls.port.empty() ? default_imap_port(tls_mode) : options.tls.port;
    const std::string sni = options.tls.sni.empty() ? options.tls.host : options.tls.sni;

    MAILXX_LOG_INFO("CLI", "Starting IMAP suite with " << imap_connection_summary(options, port));

    mailxx::imap::options client_options;
    apply_shared_security_options(client_options, options.tls, options.allow_cleartext_auth, options.require_tls_for_auth);
    mailxx::imap::client client(co_await mailxx::asio::this_coro::executor, client_options);
    mailxx::asio::ssl::context tls_ctx(mailxx::asio::ssl::context::tls_client);

    auto connect_res = co_await client.connect(options.tls.host, port, tls_mode,
        tls_mode == mailxx::net::tls_mode::none ? nullptr : &tls_ctx, sni);
    if (!record_result(recorder, "connect", std::move(connect_res), [&]
        {
            return "Connected to " + options.tls.host + ":" + port;
        }))
    {
        co_return recorder.exit_code();
    }

    auto greeting_res = co_await client.read_greeting();
    if (!record_result(recorder, "greeting", std::move(greeting_res), [](const mailxx::imap::response& response)
        {
            return summarize_imap_response(response);
        }))
    {
        co_return recorder.exit_code();
    }

    auto capability_res = co_await client.capability();
    if (!record_result(recorder, "capability_pre_tls", std::move(capability_res), [](const mailxx::imap::response& response)
        {
            return summarize_imap_response(response);
        }))
    {
        co_return recorder.exit_code();
    }

    if (tls_mode == mailxx::net::tls_mode::starttls)
    {
        auto starttls_res = co_await client.start_tls(tls_ctx, sni);
        if (!record_result(recorder, "starttls", std::move(starttls_res), [&]
            {
                return "TLS upgrade completed";
            }))
        {
            co_return recorder.exit_code();
        }

        auto capability_tls_res = co_await client.capability();
        if (!record_result(recorder, "capability_post_tls", std::move(capability_tls_res), [](const mailxx::imap::response& response)
            {
                return summarize_imap_response(response);
            }))
        {
            co_return recorder.exit_code();
        }
    }

    bool authenticated = false;
    if (!options.username.empty() && !options.secret.empty())
    {
        const auto method = parse_imap_auth_method(options.auth_method);
        if (method == mailxx::imap::auth_method::login)
        {
            auto login_res = co_await client.login(options.username, options.secret);
            if (!record_result(recorder, "auth", std::move(login_res), [&](const mailxx::imap::response& response)
                {
                    authenticated = true;
                    return summarize_imap_response(response);
                }))
            {
                co_return recorder.exit_code();
            }
        }
        else
        {
            mailxx::imap::credentials credentials{options.username, options.secret};
            auto auth_res = co_await client.authenticate(std::move(credentials), method);
            if (!record_result(recorder, "auth", std::move(auth_res), [&](const mailxx::imap::response& response)
                {
                    authenticated = true;
                    return summarize_imap_response(response);
                }))
            {
                co_return recorder.exit_code();
            }
        }
    }
    else
    {
        recorder.skip("auth", "No --username/--secret provided");
    }

    if (!authenticated)
    {
        recorder.skip("noop", "Skipped because IMAP authentication did not run");
        recorder.skip("list", "Skipped because IMAP authentication did not run");
        recorder.skip("select", "Skipped because IMAP authentication did not run");
        recorder.skip("search", "Skipped because IMAP authentication did not run");
        recorder.skip("fetch", "Skipped because IMAP authentication did not run");
    }
    else
    {
        auto noop_res = co_await client.noop();
        if (!record_result(recorder, "noop", std::move(noop_res), [](const mailxx::imap::response& response)
            {
                return summarize_imap_response(response);
            }))
        {
            co_return recorder.exit_code();
        }

        auto list_res = co_await client.list("", "*");
        if (!record_result(recorder, "list", std::move(list_res), [](const std::pair<mailxx::imap::response, std::vector<mailxx::imap::mailbox_folder>>& value)
            {
                std::vector<std::string> folders;
                for (const auto& folder : value.second)
                    folders.push_back(folder.name);
                std::ostringstream detail;
                detail << summarize_imap_response(value.first) << " folders=" << folders.size();
                if (!folders.empty())
                    detail << " [" << truncate_copy(join_strings(folders), 200) << ']';
                return detail.str();
            }))
        {
            co_return recorder.exit_code();
        }

        auto select_res = co_await client.select(options.mailbox);
        if (!record_result(recorder, "select", std::move(select_res), [](const std::pair<mailxx::imap::response, mailxx::imap::mailbox_stat>& value)
            {
                std::ostringstream detail;
                detail << summarize_imap_response(value.first) << ' ' << summarize_mailbox_stat(value.second);
                return detail.str();
            }))
        {
            co_return recorder.exit_code();
        }

        auto search_res = co_await client.uid_search(options.search);
        if (!record_result(recorder, "search", std::move(search_res), [](const std::vector<std::uint32_t>& ids)
            {
                std::ostringstream detail;
                detail << "uids=" << ids.size();
                if (!ids.empty())
                    detail << " first=" << ids.front();
                return detail.str();
            }))
        {
            co_return recorder.exit_code();
        }

        auto ids_res = co_await client.uid_search(options.search);
        if (!ids_res)
        {
            (void)recorder.fail("fetch_prepare", ids_res.error());
            co_return recorder.exit_code();
        }

        std::uint32_t selected_uid = 0;
        if (options.uid.has_value())
            selected_uid = *options.uid;
        else if (!ids_res->empty())
            selected_uid = ids_res->front();

        if (selected_uid == 0)
        {
            recorder.skip("fetch", "No UID available for fetch");
        }
        else
        {
            auto fetch_res = co_await client.uid_fetch_rfc822(selected_uid);
            if (!record_result(recorder, "fetch", std::move(fetch_res), [&](const mailxx::message& message)
                {
                    std::ostringstream detail;
                    detail << "uid=" << selected_uid << " subject=\"" << truncate_copy(message.subject()) << '"';
                    return detail.str();
                }))
            {
                co_return recorder.exit_code();
            }
        }
    }

    auto logout_res = co_await client.logout();
    if (!record_result(recorder, "logout", std::move(logout_res), [](const mailxx::imap::response& response)
        {
            return summarize_imap_response(response);
        }))
    {
        co_return recorder.exit_code();
    }

    co_return recorder.exit_code();
}

mailxx::asio::awaitable<int> run_pop3_suite(const pop3_cli_options& options, scenario_recorder& recorder)
{
    const auto tls_mode = parse_tls_mode(options.tls.tls_mode);
    const std::string port = options.tls.port.empty() ? default_pop3_port(tls_mode) : options.tls.port;
    const std::string sni = options.tls.sni.empty() ? options.tls.host : options.tls.sni;

    MAILXX_LOG_INFO("CLI", "Starting POP3 suite with " << pop3_connection_summary(options, port));

    mailxx::pop3::options client_options;
    apply_shared_security_options(client_options, options.tls, options.allow_cleartext_auth, options.require_tls_for_auth);
    mailxx::pop3::client client(co_await mailxx::asio::this_coro::executor, client_options);
    mailxx::asio::ssl::context tls_ctx(mailxx::asio::ssl::context::tls_client);

    auto connect_res = co_await client.connect(options.tls.host, port, tls_mode,
        tls_mode == mailxx::net::tls_mode::none ? nullptr : &tls_ctx, sni);
    if (!record_result(recorder, "connect", std::move(connect_res), [&]
        {
            return "Connected to " + options.tls.host + ":" + port;
        }))
    {
        co_return recorder.exit_code();
    }

    auto greeting_res = co_await client.read_greeting();
    if (!record_result(recorder, "greeting", std::move(greeting_res), [](const std::string& greeting)
        {
            return truncate_copy(greeting);
        }))
    {
        co_return recorder.exit_code();
    }

    auto capa_res = co_await client.capa();
    mailxx::pop3::capabilities capabilities;
    if (!record_result(recorder, "capa_pre_tls", std::move(capa_res), [&](const mailxx::pop3::capabilities& caps)
        {
            capabilities = caps;
            return summarize_pop3_capabilities(caps);
        }))
    {
        co_return recorder.exit_code();
    }

    if (tls_mode == mailxx::net::tls_mode::starttls)
    {
        auto starttls_res = co_await client.start_tls(tls_ctx, sni);
        if (!record_result(recorder, "starttls", std::move(starttls_res), [&]
            {
                return "TLS upgrade completed";
            }))
        {
            co_return recorder.exit_code();
        }

        auto capa_tls_res = co_await client.capa();
        if (!record_result(recorder, "capa_post_tls", std::move(capa_tls_res), [&](const mailxx::pop3::capabilities& caps)
            {
                capabilities = caps;
                return summarize_pop3_capabilities(caps);
            }))
        {
            co_return recorder.exit_code();
        }
    }

    bool authenticated = false;
    if (!options.username.empty() && !options.secret.empty())
    {
        switch (parse_pop3_auth_method(options.auth_method))
        {
            case mailxx::pop3::pop3_base::auth_method_t::LOGIN:
            {
                auto login_res = co_await client.login(options.username, options.secret);
                if (!record_result(recorder, "auth", std::move(login_res), [&]
                    {
                        authenticated = true;
                        return "USER/PASS authentication succeeded";
                    }))
                {
                    co_return recorder.exit_code();
                }
                break;
            }
            case mailxx::pop3::pop3_base::auth_method_t::PLAIN:
            {
                auto plain_res = co_await client.auth_plain(options.username, options.secret);
                if (!record_result(recorder, "auth", std::move(plain_res), [&]
                    {
                        authenticated = true;
                        return "SASL PLAIN authentication succeeded";
                    }))
                {
                    co_return recorder.exit_code();
                }
                break;
            }
            case mailxx::pop3::pop3_base::auth_method_t::XOAUTH2:
            {
                auto xoauth_res = co_await client.auth_xoauth2(options.username, options.secret);
                if (!record_result(recorder, "auth", std::move(xoauth_res), [&]
                    {
                        authenticated = true;
                        return "XOAUTH2 authentication succeeded";
                    }))
                {
                    co_return recorder.exit_code();
                }
                break;
            }
            case mailxx::pop3::pop3_base::auth_method_t::APOP:
            {
                auto apop_res = co_await client.apop(options.username, options.secret);
                if (!record_result(recorder, "auth", std::move(apop_res), [&]
                    {
                        authenticated = true;
                        return "APOP authentication succeeded";
                    }))
                {
                    co_return recorder.exit_code();
                }
                break;
            }
        }
    }
    else
    {
        recorder.skip("auth", "No --username/--secret provided");
    }

    if (!authenticated)
    {
        recorder.skip("stat", "Skipped because POP3 authentication did not run");
        recorder.skip("list", "Skipped because POP3 authentication did not run");
        recorder.skip("uidl", "Skipped because POP3 authentication did not run");
        recorder.skip("noop", "Skipped because POP3 authentication did not run");
        recorder.skip("top", "Skipped because POP3 authentication did not run");
        recorder.skip("retr", "Skipped because POP3 authentication did not run");
        recorder.skip("retr_message", "Skipped because POP3 authentication did not run");
    }
    else
    {
        auto stat_res = co_await client.stat();
        if (!record_result(recorder, "stat", std::move(stat_res), [](const mailxx::pop3::mailbox_stat& stat)
            {
                return summarize_pop3_stat(stat);
            }))
        {
            co_return recorder.exit_code();
        }

        auto list_res = co_await client.list();
        mailxx::pop3::message_list message_list;
        if (!record_result(recorder, "list", std::move(list_res), [&](const mailxx::pop3::message_list& list)
            {
                message_list = list;
                std::ostringstream detail;
                detail << "messages=" << list.size();
                if (!list.empty())
                    detail << " first=" << list.begin()->first << ':' << list.begin()->second;
                return detail.str();
            }))
        {
            co_return recorder.exit_code();
        }

        if (capabilities.uidl)
        {
            auto uidl_res = co_await client.uidl();
            if (!record_result(recorder, "uidl", std::move(uidl_res), [](const mailxx::pop3::uidl_list& uidls)
                {
                    std::ostringstream detail;
                    detail << "uidls=" << uidls.size();
                    if (!uidls.empty())
                        detail << " first=" << uidls.begin()->first << ':' << truncate_copy(uidls.begin()->second);
                    return detail.str();
                }))
            {
                co_return recorder.exit_code();
            }
        }
        else
        {
            recorder.skip("uidl", "Server did not advertise UIDL");
        }

        auto noop_res = co_await client.noop();
        if (!record_result(recorder, "noop", std::move(noop_res), [&]
            {
                return "NOOP succeeded";
            }))
        {
            co_return recorder.exit_code();
        }

        unsigned int selected_message = options.message_no;
        if (message_list.find(selected_message) == message_list.end())
        {
            if (!message_list.empty())
                selected_message = message_list.begin()->first;
            else
                selected_message = 0;
        }

        if (selected_message == 0)
        {
            recorder.skip("top", "Mailbox is empty");
            recorder.skip("retr", "Mailbox is empty");
            recorder.skip("retr_message", "Mailbox is empty");
        }
        else
        {
            if (capabilities.top)
            {
                auto top_res = co_await client.top(selected_message, options.top_lines);
                if (!record_result(recorder, "top", std::move(top_res), [&](const std::string& text)
                    {
                        std::ostringstream detail;
                        detail << "message=" << selected_message << " bytes=" << text.size()
                               << " preview=\"" << truncate_copy(text) << '"';
                        return detail.str();
                    }))
                {
                    co_return recorder.exit_code();
                }
            }
            else
            {
                recorder.skip("top", "Server did not advertise TOP");
            }

            auto retr_res = co_await client.retr(selected_message);
            if (!record_result(recorder, "retr", std::move(retr_res), [&](const std::string& text)
                {
                    std::ostringstream detail;
                    detail << "message=" << selected_message << " bytes=" << text.size()
                           << " preview=\"" << truncate_copy(text) << '"';
                    return detail.str();
                }))
            {
                co_return recorder.exit_code();
            }

            auto retr_message_res = co_await client.retr_message(selected_message);
            if (!record_result(recorder, "retr_message", std::move(retr_message_res), [&](const mailxx::message& message)
                {
                    std::ostringstream detail;
                    detail << "message=" << selected_message << " subject=\"" << truncate_copy(message.subject()) << '"';
                    return detail.str();
                }))
            {
                co_return recorder.exit_code();
            }
        }
    }

    auto quit_res = co_await client.quit();
    if (!record_result(recorder, "quit", std::move(quit_res), [&]
        {
            return "QUIT succeeded";
        }))
    {
        co_return recorder.exit_code();
    }

    co_return recorder.exit_code();
}

} // namespace

int main(int argc, char** argv)
{
    global_options global;
    smtp_cli_options smtp;
    imap_cli_options imap;
    pop3_cli_options pop3;

    CLI::App app("mailxx CLI11 real-world validation tool");
    app.set_help_all_flag("--help-all", "Expand all help");

    app.add_option("--log-level", global.log_level, "Log level: trace, debug, info, warn, error, fatal, off")
        ->check(CLI::IsMember({"trace", "debug", "info", "warn", "error", "fatal", "off"}, CLI::ignore_case));
    app.add_flag("--trace", global.trace, "Enable protocol traces from mailxx");
    app.add_flag_function("--hide-source",
        [&global](std::int64_t)
        {
            global.show_source = false;
        },
        "Hide source file and line from log output");
    app.add_flag("--stop-on-error", global.stop_on_error, "Stop the suite after the first failure");
    app.add_option("--suite-timeout-sec", global.suite_timeout_sec, "Abort the suite if it exceeds this duration in seconds");
    app.add_option("--log-file", global.log_file, "Write logs to a file as well as stderr");

    auto* smtp_cmd = app.add_subcommand("smtp", "Run the SMTP real-world validation suite");
    add_common_security_flags(*smtp_cmd, smtp);
    add_auth_flags(*smtp_cmd, smtp, {"auto_detect", "plain", "login", "xoauth2"});
    smtp_cmd->add_option("--hello-domain", smtp.hello_domain, "Domain sent in EHLO");
    smtp_cmd->add_option("--from", smtp.from, "Envelope/header sender address");
    smtp_cmd->add_option("--from-name", smtp.from_name, "Display name for the sender");
    smtp_cmd->add_option("--to", smtp.to, "Recipient address (repeatable)");
    smtp_cmd->add_option("--to-name", smtp.to_name, "Display name for recipients");
    smtp_cmd->add_option("--subject", smtp.subject, "Base message subject");
    smtp_cmd->add_option("--body", smtp.body, "Base message body");
    smtp_cmd->add_option("--attachment", smtp.attachments, "Attachment file (repeatable)")
        ->check(CLI::ExistingFile);

    auto* imap_cmd = app.add_subcommand("imap", "Run the IMAP real-world validation suite");
    add_common_security_flags(*imap_cmd, imap);
    add_auth_flags(*imap_cmd, imap, {"auto_detect", "plain", "login", "xoauth2"});
    imap_cmd->add_option("--mailbox", imap.mailbox, "Mailbox to select");
    imap_cmd->add_option("--search", imap.search, "UID SEARCH criteria");
    imap_cmd->add_option("--uid", imap.uid, "Specific UID to fetch after search");

    auto* pop3_cmd = app.add_subcommand("pop3", "Run the POP3 real-world validation suite");
    add_common_security_flags(*pop3_cmd, pop3);
    add_auth_flags(*pop3_cmd, pop3, {"login", "plain", "xoauth2", "apop"});
    pop3_cmd->add_option("--message-no", pop3.message_no, "Message number used for TOP/RETR checks");
    pop3_cmd->add_option("--top-lines", pop3.top_lines, "Number of body lines requested with TOP");

    app.require_subcommand(1);

    try
    {
        app.parse(argc, argv);
    }
    catch (const CLI::ParseError& e)
    {
        return app.exit(e);
    }

    try
    {
        configure_logging(global);

        if (*smtp_cmd)
        {
            return run_suite("SMTP Suite", global.stop_on_error, global.suite_timeout_sec, [&](scenario_recorder& recorder)
            {
                return run_smtp_suite(smtp, recorder);
            });
        }

        if (*imap_cmd)
        {
            return run_suite("IMAP Suite", global.stop_on_error, global.suite_timeout_sec, [&](scenario_recorder& recorder)
            {
                return run_imap_suite(imap, recorder);
            });
        }

        if (*pop3_cmd)
        {
            return run_suite("POP3 Suite", global.stop_on_error, global.suite_timeout_sec, [&](scenario_recorder& recorder)
            {
                return run_pop3_suite(pop3, recorder);
            });
        }
    }
    catch (const std::exception& ex)
    {
        std::cerr << "Fatal error: " << ex.what() << '\n';
        return 3;
    }

    return 0;
}
